name: rtap_fir
description: Interface for loading rePhase data onto an rTap device

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.5.0
  quick_usb: ^0.3.1
  binary: ^3.0.1

dependency_overrides:
  file_picker: ^4.6.1

dev_dependencies:
  #flutter_test:
  #  sdk: flutter
  test: ^1.24.6
  file: ^7.0.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - static/

  # fonts:
  #   - family: TODO
  #     fonts:
  #       - asset: TODO.ttf
  #       - asset: TODO.ttf
  #         style: italic